import Aviosalon from "../../assets/pictures/projects/aviosalon.jpg";
import Hotel from "../../assets/pictures/projects/hotel.jpg";
import Zverimex from "../../assets/pictures/projects/zverimex.jpg";
import AnketaPhp from "../../assets/pictures/projects/hotel.jpg";
import Kolosalon from "../../assets/pictures/projects/kolosalon.jpg";
import CountdownDays from "../../assets/pictures/projects/CountdownDays.jpg";
import Inventory from "../../assets/pictures/projects/Inventory.jpg";
import WeatherApp from "../../assets/pictures/projects/WeatherApp.jpg";
import Schoolapp from "../../assets/pictures/projects/schoolapp.jpg";
import Javaweatherapp from "../../assets/pictures/projects/javaweatherapp.jpg";
import Portfolio from "../../assets/pictures/projects/portfolio.jpg";

export const ProjectsDatabase = [
  {
    id: 1,
    title: "První cvičný web",
    description:
      "první responzivní webové stránky doplněné o\u00a0objednávkový formulář",
    description1: "",
    description2: "",
    technology: "HTML / CSS / JavaScript",
    image: Aviosalon,
    name: "HTML stránky Aviosalon",
    gitHub: "https://github.com/Monterea/Aviosalon",
    link: "https://stumi.eu/aviosalon/aviosalon.html",
  },
  {
    id: 2,
    title: "Cvičný web",
    description: "responzivní webové stránky v\u00a0Bootstrapu ",
    description1: "webové stránky vytvořené v\u00a0kurzu",
    description2: "časové zadání: 8 hodin",
    technology: "HTML / CSS / BOTSTRAP",
    image: Hotel,
    name: "BOTSTRAP stránky Aviosalon",
    gitHub: "https://github.com/Monterea/hotel-web-sites",
    link: "https://stumi.eu/hotel/index_h.html",
  },
  {
    id: 3,
    title: "Objednávkový formulář",
    description: "responzivní formulář vytvořený v\u00a0kurzu",
    description1: "časové zadání:",
    description2: "WWW stránky 8 hodin, objednávkový formulář 4 hodiny",
    technology: "HTML / CSS / JavaScript",
    image: Zverimex,
    name: "www stánky a javascriptový formulář",
    gitHub: "https://github.com/Monterea/zverimex",
    link: "https://stumi.eu/zverimex/index_zverimex.html",
  },
  {
    id: 4,
    title: "Anketní formulář",
    description: "anketní formulář vytvořený v\u00a0kurzu",
    description1: "časové zadání:",
    description2: "WWW stránky 8 hodin, objednávkový formulář 4 hodiny",
    technology: "HTML / CSS / JavaScript",
    image: AnketaPhp,
    name: "anketní formulář v PHP",
    gitHub: "https://github.com/Monterea/php-anketa",
    link: "https://stumi.eu/php/hlavni.php",
  },
  {
    id: 5,
    title: "Objednávkový formulář",
    description: "objednávkový formulář vytvořený v\u00a0kurzu",
    description1: "časové zadání: 8 hodin",
    description2: "",
    technology: "REACT",
    image: Kolosalon,
    name: "objednávkový formulář v Reactu",
    gitHub: "https://github.com/Monterea/kolosalon",
    link: "https://stumi.eu/react/index.html",
  },
  {
    id: 6,
    title: "Countdown days app",
    description: "mobilní aplikace na\u00a0zjištění pořtu dnů do\u00a0události",
    description1: "aplikace vytvořená v\u00a0kurzu",
    description2: "",
    technology: "Xamarine",
    image: CountdownDays,
    name: "aplikace CountdownDays v Xamarine",
    gitHub: "https://github.com/Monterea/CountdownDays",
    link: "",
  },
  {
    id: 7,
    title: "Invertory app",
    description: "mobilní inventurní aplikace s\u00a0vnitřní databází",
    description1: "aplikace vytvořená v\u00a0kurzu",
    description2: "",
    technology: "Xamarine",
    image: Inventory,
    name: "aplikace Inventory v Xamarine",
    gitHub: "https://github.com/Monterea/Inventory",
    link: "",
  },
  {
    id: 8,
    title: "Weather app",
    description:
      "mobilní aplikace propojená s\u00a0webovou aplikací zjišťující aktuální počasí",
    description1: "aplikace vytvořená v\u00a0kurzu",
    description2: "",
    technology: "Xamarine",
    image: WeatherApp,
    name: "aplikace WeatherApp v Xamarine",
    gitHub: "https://github.com/Monterea/WeatherApp",
    link: "",
  },
  {
    id: 9,
    title: "Školní aplikace",
    description: "webová aplikace propojená s\u00a0databází na\u00a0serveru",
    description1: "aplikace vytvořená v\u00a0kurzu",
    description2: "",
    technology: "ASP.NET Core MVC",
    image: Schoolapp,
    name: "školní aplikace v\u00a0ASP.NET Core MVC",
    gitHub: "https://github.com/Monterea/SchoolWebApp1.git",
    link: "http://monterea.somee.com/",
  },
  {
    id: 10,
    title: "Webová aplikace počasí",
    description:
      "webová aplikace propojená s\u00a0webovou aplikací zjišťující aktuální počasí",
    description1: "aplikace vytvořená v\u00a0kurzu",
    description2: "",
    technology: "JavaSpring / JQuery",
    image: Javaweatherapp,
    name: "web WeatherApp v JavaSpring",
    gitHub: "https://github.com/Monterea/JavaSpringWeatherApp",
    link: "",
  },
  {
    id: 11,
    title: "Portfólio",
    description: "osobní responzivní www stránky",
    technology: "React",
    image: Portfolio,
    name: "osobní www stránky",
    gitHub: "https://github.com/Monterea/portfolio-react",
  },
];
